FROM ghcr.io/astral-sh/uv:python3.12-alpine@sha256:a25d04690bce3e733cee2a2779d97ae60892edb517e85f43578b80ddf625e536

ENTRYPOINT ["uvx", "mcp-proxy-for-aws==1.6.0"]
CMD ["https://estimator-gateway-rqffsb4rfu.gateway.bedrock-agentcore.us-east-1.amazonaws.com/mcp"]
